In [4]:
import numpy as np

np.array([1, 2, 3])
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
x = np.array([1, 2, 3])
print(x.dtype)
print(x.shape)
print(x.size)

int64
(3,)
3


In [8]:
x = np.array([1, 2, 3])
print(x)
x = np.append(x, [4, 5, 6])
print(x)

[1 2 3]
[1 2 3 4 5 6]


In [9]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)
y = x.reshape(2, -1)
print(y)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [10]:
x = np.array(range(1, 10))
print(x)
print(x[1::2])

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [11]:
x = np.array(range(1, 10))
print(x)
print(x[::-2])

[1 2 3 4 5 6 7 8 9]
[9 7 5 3 1]


In [13]:
x = np.array(range(1, 10))
print(x)
print(x[x > 5])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [14]:
np.linspace(0, 10, num = 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [16]:
np.random.rand(10, 1)

array([[0.06450152],
       [0.42787972],
       [0.14531772],
       [0.40677555],
       [0.35865402],
       [0.49747832],
       [0.83248364],
       [0.24545039],
       [0.17962305],
       [0.86046525]])

In [17]:
x = np.array(range(1, 10))
np.random.shuffle(x)
print(x)

[9 8 4 6 2 1 5 7 3]


In [18]:
x = np.array(range(1, 10))
np.random.shuffle(x)
print(x)
y = np.sort(x)[::-1]
print(y)

[7 2 3 1 8 9 5 4 6]
[9 8 7 6 5 4 3 2 1]


In [20]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.vstack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]
